"""Phase 3 (cont.): render a Diagnosis to ``report.md`` + ``report.json``.

Reports land under ``<dest_root>/<jobid>/`` (default ``/data/jobs/.slurm-doctor``).
The markdown is human-first; the JSON is machine-first and schema-versioned.
"""
from __future__ import annotations

import json
import os
from dataclasses import asdict
from pathlib import Path

from . import SCHEMA_VERSION
from .collect import CollectedBundle
from .diagnose import Diagnosis, ProposedFix


DEFAULT_REPORT_ROOT = Path("/data/jobs/.slurm-doctor")


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------

def render_markdown(diag: Diagnosis, bundle: CollectedBundle) -> str:
    parts: list[str] = []
    parts.append(f"# slurm-doctor: job {diag.jobid}")
    parts.append("")
    parts.append("## TL;DR")
    parts.append("")
    parts.append(diag.tldr or "_(no summary)_")
    parts.append("")
    parts.append(_what_ran(bundle))
    parts.append("")
    parts.append(_why_it_failed(diag, bundle))
    parts.append("")
    parts.append(_suggested_fixes(diag))
    parts.append("")
    parts.append(_verification_plan(diag, bundle))
    parts.append("")
    parts.append("---")
    parts.append(f"_Generated by slurm-doctor (schema v{SCHEMA_VERSION}); "
                 f"raw bundle: `{bundle.cache_dir}`_")
    parts.append("")
    return "\n".join(parts)


def _what_ran(bundle: CollectedBundle) -> str:
    lines = ["## What ran", ""]
    lines.append("| Field | Value |")
    lines.append("|---|---|")
    rows = [
        ("JobID", bundle.jobid),
        ("State", bundle.state),
        ("ExitCode", bundle.exit_code),
        ("DerivedExitCode", bundle.derived_exit_code),
        ("Reason", bundle.reason),
        ("NodeList", bundle.nodelist),
        ("WorkDir", bundle.workdir),
        ("ReqMem", bundle.req_mem),
        ("MaxRSS", bundle.max_rss),
        ("Elapsed", bundle.elapsed),
        ("Timelimit", bundle.timelimit),
        ("Start", bundle.start_time),
        ("End", bundle.end_time),
        ("AllocTRES", bundle.alloc_tres),
    ]
    for label, value in rows:
        if value in (None, "", "None"):
            continue
        lines.append(f"| {label} | `{value}` |")
    return "\n".join(lines)


def _why_it_failed(diag: Diagnosis, bundle: CollectedBundle) -> str:
    lines = ["## Why it failed", ""]
    lines.append(f"**Root cause:** {diag.root_cause} _(confidence {diag.confidence:.2f})_")
    lines.append("")

    if diag.state_evidence:
        lines.append("**SLURM state machine:**")
        for e in diag.state_evidence:
            lines.append(f"- {e}")
        lines.append("")

    if diag.rule_hits:
        lines.append("**Pattern rules matched:**")
        for h in diag.rule_hits:
            lines.append(f"- **{h['title']}** "
                         f"_(rule `{h['rule_id']}`, category `{h['category']}`, "
                         f"confidence {h['confidence']:.2f})_")
            for ev in h["evidence"]:
                lines.append(f"  > `{ev}`")
            hint = (h.get("hint") or "").strip()
            if hint:
                hint_lines = [ln for ln in hint.splitlines() if ln.strip()]
                lines.append(f"  Hint: {' '.join(hint_lines)}")
        lines.append("")

    if diag.contributing_factors:
        lines.append("**Contributing factors:** "
                     + "; ".join(diag.contributing_factors))
        lines.append("")

    return "\n".join(lines)


def _suggested_fixes(diag: Diagnosis) -> str:
    lines = ["## Suggested fixes", ""]
    if not diag.proposed_fixes:
        lines.append("_No safe fix proposed. Investigate the evidence above._")
        return "\n".join(lines)

    # rank by confidence desc, then declaration order
    ordered = sorted(
        enumerate(diag.proposed_fixes), key=lambda iv: (-iv[1].confidence, iv[0])
    )
    for idx, (_origi, fix) in enumerate(ordered, start=1):
        gate = "auto-applicable" if not fix.requires_yes else "needs --yes"
        lines.append(
            f"### {idx}. `{fix.fix_kind}` — {fix.description} "
            f"_(confidence {fix.confidence:.2f}, {gate})_"
        )
        lines.append("")
        lines.append(f"**Why:** {fix.rationale}")
        lines.append("")
        if fix.diff:
            lines.append("```diff")
            lines.append(fix.diff.rstrip())
            lines.append("```")
        elif fix.patched_script_path:
            lines.append(f"_Patched script: `{fix.patched_script_path}`_")
        else:
            lines.append(
                "_(Diff will be generated when you run "
                f"`slurm-doctor patch {diag.jobid}` — Phase 4.)_"
            )
        lines.append("")
    return "\n".join(lines)


def _verification_plan(diag: Diagnosis, bundle: CollectedBundle) -> str:
    lines = ["## Verification plan", ""]
    lines.append(
        f"1. Apply the top-ranked fix: `slurm-doctor patch {diag.jobid}` "
        "(or `heal --yes` if you trust the fix kind)."
    )
    lines.append(
        f"2. Inspect the patched script under `{bundle.workdir or '<workdir>'}/"
        f"<script>.fix1.sh` before submitting."
    )
    lines.append(
        f"3. Submit with `sbatch --dependency=afternotok:{diag.jobid} "
        "<patched>.sh` so it only runs if the original didn't recover."
    )
    lines.append(
        "4. After completion, re-run `slurm-doctor suggest <newjobid>` and "
        "confirm the failure category changed (or is gone)."
    )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# JSON
# ---------------------------------------------------------------------------

def render_json(diag: Diagnosis, bundle: CollectedBundle) -> dict:
    return {
        "schema_version": SCHEMA_VERSION,
        "jobid": diag.jobid,
        "diagnosis": diag.to_dict(),
        "bundle": {
            "cache_dir": bundle.cache_dir,
            "state": bundle.state,
            "exit_code": bundle.exit_code,
            "nodelist": bundle.nodelist,
        },
    }


# ---------------------------------------------------------------------------
# Write
# ---------------------------------------------------------------------------

def write_report(
    diag: Diagnosis,
    bundle: CollectedBundle,
    *,
    dest_root: str | os.PathLike[str] | None = None,
) -> tuple[Path, Path]:
    root = Path(dest_root) if dest_root is not None else DEFAULT_REPORT_ROOT
    out_dir = root / str(diag.jobid)
    out_dir.mkdir(parents=True, exist_ok=True)
    md = out_dir / "report.md"
    js = out_dir / "report.json"
    md.write_text(render_markdown(diag, bundle))
    js.write_text(json.dumps(render_json(diag, bundle), indent=2, default=str))
    return md, js
